const assert = require('assert')
const { makeManager } = require('./test-utils')
const { manager } = makeManager({ auth: { mode: 'dev-shared-token', devToken: 't' }, network: { domain: 'local', hostnamePrefix: 'espdisp', namingPolicy: 'device-id' } })
manager.store.firmware.artifacts.push({ artifactId: 'fw-1', version: '0.5.0', file: { path: '/tmp/firmware-factory.bin', name: 'firmware-factory.bin', sha256: 'abc', size: 2202336, contentType: 'application/octet-stream' } })
const man = manager.firmwareManifest('fw-1')
assert.equal(man.name, 'yey-display')
assert.equal(man.version, '0.5.0')
assert.ok(Array.isArray(man.builds))
assert.equal(man.builds[0].chipFamily, 'ESP32-S3')
assert.equal(man.builds[0].parts[0].offset, 0)
assert.ok(/\/firmware\/artifacts\/fw-1\/binary$/.test(man.builds[0].parts[0].path))
assert.equal(manager.firmwareManifest('nope'), null)
const file = manager.firmwareArtifactFile('fw-1')
assert.equal(file.path, '/tmp/firmware-factory.bin')
assert.equal(manager.firmwareArtifactFile('nope'), null)
console.log('manifest.test: OK')
