const assert = require('assert')
const { makeManager } = require('./test-utils')
const { MockFirmware } = require('./mock-firmware')
const { manager, auth } = makeManager({ auth: { mode: 'dev-shared-token', devToken: 't' }, network: { domain: 'local', hostnamePrefix: 'espdisp', namingPolicy: 'device-id' } })
const v0 = manager.validateOtaTarget('nope')
assert.equal(v0.exists, false); assert.equal(v0.ready, false)
const dev = new MockFirmware(manager, { deviceId: 'espdisp-ota-1', auth, display: { width: 480, height: 480, shape: 'square', rotation: 0, colorDepth: 16 } })
dev.register()
const v1 = manager.validateOtaTarget('espdisp-ota-1')
assert.equal(v1.exists, true); assert.equal(typeof v1.online, 'boolean'); assert.equal(v1.hasArtifact, false); assert.equal(v1.ready, false)
manager.store.firmware.artifacts.push({ artifactId: 'fw-1', version: '0.5.0', file: { path: '/tmp/x.bin', name: 'x.bin' } })
const v2 = manager.validateOtaTarget('espdisp-ota-1')
assert.equal(v2.hasArtifact, true)
assert.equal(v2.ready, v2.exists && v2.online && v2.hasArtifact && v2.addressKnown)
console.log('ota-validate.test: OK')
