const assert = require('assert')
const { makeManager } = require('./test-utils')
const { MockFirmware } = require('./mock-firmware')
const { manager, auth } = makeManager({ auth: { mode: 'dev-shared-token', devToken: 't' }, network: { domain: 'local', hostnamePrefix: 'espdisp', namingPolicy: 'device-id' } })
manager.updateSettings({ numbering: { prefix: 'boat-', pad: 2, next: 7 } })
const dev = new MockFirmware(manager, { deviceId: 'espdisp-aaaaaaaaaaaa', auth, name: '', display: { width: 480, height: 480, shape: 'square', rotation: 0, colorDepth: 16 } })
dev.register()
const rec = manager.store.registry.devices['espdisp-aaaaaaaaaaaa']
assert.equal(rec.assignedNumber, 'boat-07', 'new device got the next number')
assert.equal(rec.name, 'boat-07', 'name set to the assigned number')
assert.equal(manager.getSettings().numbering.next, 8, 'counter advanced once')
dev.register()
assert.equal(manager.store.registry.devices['espdisp-aaaaaaaaaaaa'].assignedNumber, 'boat-07', 're-register keeps number')
assert.equal(manager.getSettings().numbering.next, 8, 'counter not advanced on re-register')
console.log('provision-number.test: OK')
