const assert = require('assert')
const { makeManager } = require('./test-utils')
const { MockFirmware } = require('./mock-firmware')
const { manager, auth } = makeManager({ auth: { mode: 'dev-shared-token', devToken: 't' }, network: { domain: 'local', hostnamePrefix: 'espdisp', namingPolicy: 'device-id' } })
manager.updateSettings({ ota: { password: 'flashpw' } })
const dev = new MockFirmware(manager, { deviceId: 'espdisp-bbbbbbbbbbbb', auth, display: { width: 480, height: 480, shape: 'square', rotation: 0, colorDepth: 16 } })
dev.register()
const cfg = manager.generateConfig('espdisp-bbbbbbbbbbbb')
assert.ok(cfg.ota, 'has ota section')
assert.equal(cfg.ota.password, 'flashpw', 'config carries the OTA password from system settings')
manager.store.settings.ota.password = ''
const cfg2 = manager.generateConfig('espdisp-bbbbbbbbbbbb')
assert.ok(!cfg2.ota || !cfg2.ota.password, 'no password -> not pushed')
console.log('provision-config.test: OK')
